apiVersion: v1
kind: Pod
metadata:
  name: iowrite
  labels:
    app: iowrite
  namespace: volume-fun
spec:
  containers:
    - name: iowrite
      image: "quay.io/rhpowell_mobb/volume_fun:latest"
      volumeMounts:
        - mountPath: /data1
          name: data1
  volumes:
    - name: data1
      persistentVolumeClaim:
        claimName: rhys-claim
