kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rhys-claim
  namespace: volume-fun
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: gp2-csi
  volumeMode: Filesystem
